### ISSUE TITLE
Kubernetes install error

### ISSUE THREAD

**Issue by jouros** [XenitAB/azdo-proxy#35]
I get successful docker build but when I do helm install I get this error:
$ kubectl logs azdo-proxy-5996584b78-s8729

{"level":"info","ts":1628600090.3676434,"logger":"main","caller":"build/main.go:60","msg":"read configuration from","path":"/var/config.json"}

{"level":"info","ts":1628600090.3677375,"logger":"main","caller":"build/main.go:61","msg":"serve metrics","port":":9090","endpoint":"/metrics"}

{"level":"error","ts":1628600090.3677878,"logger":"main","caller":"build/main.go:53","msg":"run error","error":"could not load configuration: invalid character 'c' looking for beginning of value","stacktrace":"main.main\n\t/build/main.go:53\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

**Comment by simongottschlag** [comment]
Hi @jouros!

Would it be possible for you to paste the values you are using with helm? Please redact anything sensitive.

**Comment by jouros** [comment]
I had config.json almost same as a default example, only had real PAT included in "pat:" line. I did my own Azure DevOps pipeline build for azdo-proxy container, so I just had repository pointing to my acr and imagePullSecrets set in values.yaml, I also changed version tags to 0.4.1 not v0.4.1, that's all. I also did fresh git pull into this repo before build.

**Comment by simongottschlag** [comment]
Would it be possible for you to share your Helm values? It would make it a bit easier for me to troubleshoot. :)

**Comment by jouros** [comment]
```
$ cat Chart.yaml
apiVersion: v2
name: azdo-proxy
description: A Helm chart for azdo-proxy
type: application
version: 0.4.1
appVersion: 0.4.1
```

```
$ cat values.yaml
replicaCount: 1

image:
  repository: [ACR]/azdo-proxy
  pullPolicy: IfNotPresent
  tag: "0.4.1"

imagePullSecrets:
  - name: dockerpull

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  metricsPort: 9090

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

servicemonitor:
  enabled: false

networkPolicy:
  enabled: false

  #priorityClassName: ""

config: "config.json"
```

```
$ cat config-json
{
  "organizations": [
    {
      "name": "org",
      "pat": "PAT IS HERE",
      "repositories": [
        {
          "name": "fleet-infra",
          "project": "lab",
          "namespaces": [
            "foo",
            "bar"
          ]
        }
      ]
    }
  ]
}
```

**Comment by simongottschlag** [comment]
Hi @jouros!

Thanks for sharing the Helm values. The config property is a string and not a reference to a config file - can you try and in-line the config like this:
https://github.com/XenitAB/terraform-modules/blob/main/modules/kubernetes/fluxcd-v2-azdo/templates/azdo-proxy-values.yaml.tpl

I'm on the phone now, but I don't think we have any way right now to use an existing secret - but should be quite easy to fix if it's required.

**Comment by jouros** [comment]
Ok, thanks, I got totally confused with that :-D I'll try that in-line way tomorrow.

**Comment by jouros** [comment]
My error was related to that mistake with config.json. 

Could I still ask about that config format: tenants are different teams working with different apps in their own repos and namespace per repo? ${azure_devops_proj} is project where cluster repo is located including per cluster, e.g. dev, staging, prod dirs and their respective flux-system directory?

**Comment by simongottschlag** [comment]
Hi, 

You should have something like this:

```json
{
   "organizations":[
      {
         "name":"azure-devops-organization-name",
         "pat":"super-user-pat",
         "repositories":[
            {
               "project":"team1-project-name",
               "name":"team1-gitops-repo-name",
               "namespaces":[
                  "team1-namespace"
               ],
               "secretNameOverride":"flux"
            },
            {
               "project":"fleet-infra-project-name",
               "name":"fleet-infra-repo-name",
               "namespaces":[
                  "flux-system"
               ],
               "secretNameOverride":"flux-system"
            }
         ]
      }
   ]
}
```

**Comment by jouros** [comment]
Thanks :)
