### ISSUE TITLE
Validate that projects with spaces in the name work

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/azdo-proxy#6]
We need to validate that projects with space in the name work.

**Comment by phillebaba** [comment]
Whitespace project names and repository names did not work because the non-escaped path was used when authenticating.
https://github.com/XenitAB/azdo-proxy/blob/a085b1c7bede1e7f071f24d20aafdaab940e8ba5/main.go#L126

Solution is to use `r.URL.EscapedPath()` instead of `r.URL.Path`.

**Comment by phillebaba** [comment]
The solution requires you to use %20 instead of spaces in the config file.
